### ISSUE TITLE
Official library?

### ISSUE THREAD

**Issue by olalonde** [TinEye/tineye-api-node#1]
https://services.tineye.com/developers/tineyeapi/libraries.html lists another library

Also, none of the methods seem to bubble errors

**Comment by tineyedev** [comment]
Yes, this will be the official node library. Still a work in progress.

Thank you for the input, I will look into the error handling.

**Comment by olalonde** [comment]
@tineyedev just sent a PR, fixes a couple of issues with error handling and introduces optional Promise based API

**Comment by olalonde** [comment]
https://github.com/TinEye/tineye_api_node/pull/2

**Comment by tineyedev** [comment]
Thanks, commented on the pull request and released v1.0.0.
